import UsersFilters from '@/components/Users/UsersFilters';
import UsersTable from '@/components/Users/UsersTable';

const users = [
  {
    id: '1',
    src: 'https://randomuser.me/api/portraits/men/1.jpg',
    fallback: 'JD',
    name: 'John Doe',
    phoneNumber: '+1 202-555-0165',
    email: 'john.doe@example.com',
    type: 'Admin',
    buildingName: 'Central Plaza',
  },
  {
    id: '2',
    src: 'https://randomuser.me/api/portraits/women/2.jpg',
    fallback: 'AS',
    name: 'Anna Smith',
    phoneNumber: '+1 202-555-0148',
    email: 'anna.smith@example.com',
    type: 'User',
    buildingName: 'Main Tower',
  },
  {
    id: '3',
    src: 'https://randomuser.me/api/portraits/men/3.jpg',
    fallback: 'RW',
    name: 'Robert White',
    phoneNumber: '+1 202-555-0102',
    email: 'robert.white@example.com',
    type: 'Manager',
    buildingName: 'West Wing',
  },
  {
    id: '4',
    src: 'https://randomuser.me/api/portraits/women/4.jpg',
    fallback: 'LC',
    name: 'Lucy Carter',
    phoneNumber: '+1 202-555-0199',
    email: 'lucy.carter@example.com',
    type: 'User',
    buildingName: 'North Block',
  },
  {
    id: '5',
    src: 'https://randomuser.me/api/portraits/men/5.jpg',
    fallback: 'MB',
    name: 'Michael Brown',
    phoneNumber: '+1 202-555-0173',
    email: 'michael.brown@example.com',
    type: 'Technician',
    buildingName: 'East End',
  },
  {
    id: '6',
    src: 'https://randomuser.me/api/portraits/women/6.jpg',
    fallback: 'ER',
    name: 'Emily Rogers',
    phoneNumber: '+1 202-555-0139',
    email: 'emily.rogers@example.com',
    type: 'User',
    buildingName: 'South Tower',
  },
  {
    id: '7',
    src: 'https://randomuser.me/api/portraits/men/7.jpg',
    fallback: 'DB',
    name: 'Daniel Brown',
    phoneNumber: '+1 202-555-0184',
    email: 'daniel.brown@example.com',
    type: 'Security',
    buildingName: 'Central Plaza',
  },
  {
    id: '8',
    src: 'https://randomuser.me/api/portraits/women/8.jpg',
    fallback: 'NG',
    name: 'Natalie Green',
    phoneNumber: '+1 202-555-0152',
    email: 'natalie.green@example.com',
    type: 'Manager',
    buildingName: 'Sunrise Apartments',
  },
  {
    id: '9',
    src: 'https://randomuser.me/api/portraits/men/9.jpg',
    fallback: 'AW',
    name: 'Andrew Wilson',
    phoneNumber: '+1 202-555-0191',
    email: 'andrew.wilson@example.com',
    type: 'User',
    buildingName: 'Lakeside Tower',
  },
  {
    id: '10',
    src: 'https://randomuser.me/api/portraits/women/10.jpg',
    fallback: 'SC',
    name: 'Sophia Clarke',
    phoneNumber: '+1 202-555-0178',
    email: 'sophia.clarke@example.com',
    type: 'Admin',
    buildingName: 'Main Tower',
  },
  {
    id: '11',
    src: 'https://randomuser.me/api/portraits/men/11.jpg',
    fallback: 'TP',
    name: 'Thomas Parker',
    phoneNumber: '+1 202-555-0126',
    email: 'thomas.parker@example.com',
    type: 'Maintenance',
    buildingName: 'Central Plaza',
  },
  {
    id: '12',
    src: 'https://randomuser.me/api/portraits/women/12.jpg',
    fallback: 'KB',
    name: 'Katherine Brooks',
    phoneNumber: '+1 202-555-0133',
    email: 'katherine.brooks@example.com',
    type: 'User',
    buildingName: 'Sunset View',
  },
  {
    id: '13',
    src: 'https://randomuser.me/api/portraits/men/13.jpg',
    fallback: 'JS',
    name: 'James Scott',
    phoneNumber: '+1 202-555-0119',
    email: 'james.scott@example.com',
    type: 'Manager',
    buildingName: 'North Block',
  },
  {
    id: '14',
    src: 'https://randomuser.me/api/portraits/women/14.jpg',
    fallback: 'VG',
    name: 'Victoria Gray',
    phoneNumber: '+1 202-555-0109',
    email: 'victoria.gray@example.com',
    type: 'User',
    buildingName: 'East End',
  },
  {
    id: '15',
    src: 'https://randomuser.me/api/portraits/men/15.jpg',
    fallback: 'EC',
    name: 'Ethan Cooper',
    phoneNumber: '+1 202-555-0168',
    email: 'ethan.cooper@example.com',
    type: 'Technician',
    buildingName: 'West Wing',
  },
  {
    id: '16',
    src: 'https://randomuser.me/api/portraits/women/16.jpg',
    fallback: 'MJ',
    name: 'Mia Johnson',
    phoneNumber: '+1 202-555-0187',
    email: 'mia.johnson@example.com',
    type: 'User',
    buildingName: 'Central Plaza',
  },
  {
    id: '17',
    src: 'https://randomuser.me/api/portraits/men/17.jpg',
    fallback: 'CM',
    name: 'Christopher Miller',
    phoneNumber: '+1 202-555-0120',
    email: 'christopher.miller@example.com',
    type: 'Manager',
    buildingName: 'Sunrise Apartments',
  },
  {
    id: '18',
    src: 'https://randomuser.me/api/portraits/women/18.jpg',
    fallback: 'EH',
    name: 'Ella Hughes',
    phoneNumber: '+1 202-555-0159',
    email: 'ella.hughes@example.com',
    type: 'Admin',
    buildingName: 'Main Tower',
  },
  {
    id: '19',
    src: 'https://randomuser.me/api/portraits/men/19.jpg',
    fallback: 'BW',
    name: 'Benjamin Walker',
    phoneNumber: '+1 202-555-0194',
    email: 'benjamin.walker@example.com',
    type: 'User',
    buildingName: 'North Block',
  },
  {
    id: '20',
    src: 'https://randomuser.me/api/portraits/women/20.jpg',
    fallback: 'AR',
    name: 'Abigail Roberts',
    phoneNumber: '+1 202-555-0135',
    email: 'abigail.roberts@example.com',
    type: 'Technician',
    buildingName: 'Sunset View',
  },
];


const Users = () => {
  return (
    <section className='w-full flex flex-col gap-6'>
      {/* Filters Section */}
      <UsersFilters />
      
      {/* Users Table */}
      <UsersTable users={users} />
    </section>
  );
};

export default Users;
